spring:
  application:
    name: smartstock-app

  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/smartstockdb?authSource=admin

app:
  client:
    id: ${APP_CLIENT_ID:ABC}
    secret: ${APP_CLIENT_SECRET:DEF}
  auth:
    url: ${APP_CLIENT_URL:http://localhost:3000/api/token}