spring:
  application:
    name: smartstock-app

  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      host: localhost
      port: 27017
      database: smartstockdb
      username: admin
      password: 123456

app:
  client:
    id: ${APP_CLIENT_ID:ABC}
    secret: ${APP_CLIENT_SECRET:DEF}